# YOLO11n Model Configuration for Table Structure Detection
model:
  name: "yolo11n"
  task: "detect"
  nc: 4  # number of classes: table, row, column, cell
  names: ["table", "row", "column", "cell"]

# Training hyperparameters
train:
  epochs: 100
  batch_size: 16
  imgsz: 640
  device: "auto"  # auto-detect GPU/TPU
  workers: 8
  patience: 10
  save_period: 5  # save checkpoint every 5 epochs

  # Optimizer settings
  optimizer: "AdamW"
  lr0: 0.001
  lrf: 0.01
  momentum: 0.937
  weight_decay: 0.0005

  # Data augmentation
  hsv_h: 0.015
  hsv_s: 0.7
  hsv_v: 0.4
  degrees: 0.0
  translate: 0.1
  scale: 0.5
  shear: 0.0
  perspective: 0.0
  flipud: 0.0
  fliplr: 0.5
  mosaic: 1.0
  mixup: 0.0
  copy_paste: 0.0

# Validation settings
val:
  batch_size: 16
  imgsz: 640
  save_json: true
  save_hybrid: false
  conf: 0.001
  iou: 0.6
  max_det: 300
  half: false

# Checkpointing
checkpoint:
  save_best: true
  save_last: true
  save_period: 5
  resume: true